global:
  scrape_interval: 5s  # Reduce interval for faster updates

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flask_app"
    static_configs:
      - targets: ["172.17.0.2:80"]  # Flask app running inside Docker
